### Zadanie 1
Stwórz serię danych zawierających pełny format daty (tj. dzień, miesiąc, rok) na podstawie informacji z list oraz biążacego roku. Następnie stwórz drugą taką serię gdzie wszystkie daty będą przesunietę o 5 dni później

Poproszę o dwa rozwiązania z użyciem:
1. samych list
2. pakietu pandas.

Roziwązanie listy:

In [3]:
months = ["Jan", "Feb", "Apr", "May"]
days = [10, 15, 12, 23]

# Deklarujemy dwie puste listy wynikowe
podstawowaLista = []
przesunietaLista = []
# Wykorzystujemy pętle z indeksami numerycznymi
for i in range(0, len(days)):
  # Dodajemy kolejne elmenety listy - odwołujemy się do i-tego elementu listy
  podstawowaLista.append(str(days[i]) + " " + months[i] + " 2021")
  przesunietaLista.append(str(days[i]+5) + " " + months[i] + " 2021")

print("Podstawowa lista:")
print(*podstawowaLista, sep = "\n")
print()

print("Przesunięta lista:")
print(*przesunietaLista, sep = "\n")

Podstawowa lista:
10 Jan 2021
15 Feb 2021
12 Apr 2021
23 May 2021

Przesunięta lista:
15 Jan 2021
20 Feb 2021
17 Apr 2021
28 May 2021

Rozwiązanie Pandas:

In [6]:
import pandas as pd 
# Komendy list i zip stworzą listę krotek, na podstawie której zrobię pandas.dataframe 
list_records = list(zip(months, days))
df = pd.DataFrame.from_records(list_records, columns=["Months", "Days"])

# W Pandas dodawanie kolumn można przeprowadzić bez użycia pętli:
df["PodstawoweDaty"] = df["Days"].astype(str) + " " + df["Months"] + " 2021" 
df["PrzesunieteDaty"] = (df["Days"]+5).astype(str) + " " + df["Months"] + " 2021" 

# Wydrukowanie - zwróćcie uwagę na dwa sposoby odwołań do kolumn
# df["PodstawoweDaty"] jest równoznaczne z df.PodstawoweDaty
print("Podstawowe daty:")
print(df.PodstawoweDaty)

print("Przesunięte daty:")
print(df.PodstawoweDaty)

0    10 Jan 2021
1    15 Feb 2021
2    12 Apr 2021
3    23 May 2021
Name: PodstawoweDaty, dtype: object 0    15 Jan 2021
1    20 Feb 2021
2    17 Apr 2021
3    28 May 2021
Name: PrzesunieteDaty, dtype: object

### Zadanie 2
Napisz pętle które stworzą listę informacji o polskich laureatach:
* pokojowej nagrody Nobla. 
* literackiej nagrody Nobla po 1980 roku

Dane o każdym laureacie przetrzymywane powinny być w krotce - tak jak w liście pol_Nobel.

Rozwiązanie podobnego problemu w Pandas przedstawiłem na dole.

In [9]:
year =[1903,	1905,	1907,	1911,	1924,	1944,	1950,	1977,	1978,	1978, 1980,	1981,	1983,	1992,	1994,	1995,	1996,	2007, 2018]
who = ["Maria Skłodowska Curie",	"Henryk Sienkiewicz",	"Albert A. Michelson",	"Maria Skłodowska Curie",	"Władysław Reymont",	"Isidor Isaac Rabi",	"Tadeusz Reichstein",	"Andrzej Schally",
       "Menachem Begin",	"Isaac Bashevis Singer",	"Czesław Miłosz",	"Roald Hoffmann",	"Lech Wałęsa",	"Jerzy Charpak",	"Shimon Peres",	"Józef Rotblat",	"Wisława Szymborska",	"Leonid Hurwicz",	"Olga Tokarczuk"]
disc = ["Physics",	"Literature",	"Physics","Chemistry", "Literature",	"Physics", "Medicine",	"Medicine",	"Peace",	"Literature",	"Literature",	"Chemistry",	"Peace",	"Physics",
        "Peace",	"Peace",	"Literature",	"Economics",	"Literature"]

# Ta lista będzie nam służyć do filtrowania
pol_Nobel = list(zip(year, who, disc))

# Pokojowy nobel - wybieramy same nazwiska osób jeżeli dziedzina to Peace: 

peaceNobel = [element[1] for element in pol_Nobel if element[2] == "Peace"]
print("Laureaci pokojowej nagrody Nobla z Polski:")
print(*peaceNobel, sep = "\n")
print()

# Literacki nobel
litNobel = [element[1] for element in pol_Nobel if element[2] == "Literature" and element[0] > 1980]
print("Współcześni laureaci literackiej nagrody Nobla z Polski:")
print(*litNobel, sep = "\n")

Laureaci pokojowej nagrody Nobla z Polski:
Menachem Begin
Lech Wałęsa
Shimon Peres
Józef Rotblat

Współcześni laureaci literackiej nagrody Nobla z Polski:
Wisława Szymborska
Olga Tokarczuk

Rozwiązanie pandas - jest objętościowo podobne, jednak kod jest znacznie bardziej czytelny. Zaczyna to przypominac bardziej wypracowanie z angielskiego:

In [ ]:
import pandas as pd
Nobel_dict = {
  "Rok": year,
  "Laureat": who,
  "Dziedzina": disc
}
df = pd.DataFrame(Nobel_dict)

print("Polscy laureaci pokojowej nagrody Nobla:")
peaceNobel = df[df["Dziedzina"] == "Peace"]
print(peaceNobel)

print()
print("Polscy laureaci literackiej nagrody Nobla po 1950:")
contemporaryLiteratureNobel = df[(df.Dziedzina == "Literature") & (df.Rok > 1980)]
print(contemporaryLiteratureNobel)

### Zadanie 3 
Usuń z listy zbędne elementy

In [11]:
list_NAs = ["Józef Piłsudski", "Edward Rydz-Śmigły", None, "Władysław Sikorski", "Kazimierz Sosnkowski", "Tadeusz Komorowski", None, "Władysław Anders"]

# Jeżeli chcemy usuwać dowolną liczbę zmiennych pustych albo liczbowych warto skorzystać z takiej pętli:
lista_bezNA = [element for element in list_NAs if isinstance(element, str)]
print(lista_bezNA)

['Józef Piłsudski', 'Edward Rydz-Śmigły', 'Władysław Sikorski', 'Kazimierz Sosnkowski', 'Tadeusz Komorowski', 'Władysław Anders']

Rozwiązanie pandas:

In [ ]:
import pandas as pd
df = pd.DataFrame(list_NAs, columns=['GISZ_IIRP'])

df = df.dropna()
print(df)

### Zadanie 4

Napisz funkcję która z każdego wyrazu tekstu wybierze pierwszą literę i złoży je w napis. Zastosuje te rozwiązania do wszystkich elementów listy.

Wykorzystaj funkcje:
* map
* split z metody string

In [13]:
imperium_trujki = ["Chcemy, żeby Czarny Anioł zbawił dla nas świat",
                   "Zebrał armię wszechpotężną nasz Niebiański Brat",
                   "Nawet jeśli zmieni przy tym w piekło cały kraj",
                   "Graj muzyko graj!",
                   "Obróci niewiernych wiarołomców znowu w proch",
                   "Nie pomogą groźby, nie pomoże matek szloch",
                   "Chcemy, żeby Czarny Anioł zabrał nas na bój!",
                   "Truj Aniele truj!"]

# Funkcja przetwarzająca tekst:
def firstLetters(napis):
  lista_slow = napis.split()
  wynik = ""
  for wyraz in lista_slow:
    # Dodaje pierwszy znak z wyrazu:
    wynik += wyraz[0]

  return wynik

# Wywolanie wszystkich elementów listy
finalnaLista = list(map(firstLetters, imperium_trujki))
print(finalnaLista)

['CżCAzdnś', 'ZawnNB', 'Njzptwpck', 'Gmg', 'Onwzwp', 'Npgnpms', 'CżCAznnb', 'TAt']

Rozwiązanie Pandas - wstaw nazwję funkcji do komenty apply:

In [15]:
import pandas as pd
df = pd.DataFrame(imperium_trujki, columns=['Hunter'])

# Aby wykonać funkcje w Pandas używamy metody apply
df['Hunter'] = df['Hunter'].apply(firstLetters)

print(df['Hunter'])

0     CżCAzdnś
1       ZawnNB
2    Njzptwpck
3          Gmg
4       Onwzwp
5      Npgnpms
6     CżCAznnb
7          TAt
Name: Hunter, dtype: object

### Zadanie 5
Wykorzystaj instrukcje [Cheat_sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) pandas, aby:

Złączyć 2 obiekty data frame: 
* po wierszach 
* po kolumnach 
* złączyć wyłącznie pasujące dane

In [20]:
df1 = pd.DataFrame( {"a" : ["x1" ,"x2", "x3"], 
                    "b" : [7, 8, 9],
                    "c" : [10, 11, 12]})
                  
df2 = pd.DataFrame( {"a" : ["x1" ,"x2", "x3"], 
                    "d" : [77, 88, 99],
                    "g" : [110, 111, 112]})

# Aby połączyć dwa obiekty DataFrame używamy komendy concat - po wierszach:
df3 = pd.concat([df1, df2])
print("Łączenie po wierszach:")
print(df3)
print()

# Aby operować na kolumnach w pandas często dodajemy argument axis = 1
df4 = pd.concat([df1, df2], axis = 1)
print("Łączenie po kolumnach:")
print(df4)
print()

# Do scalania danych wykorzystywana jest funkcja merge
df5 = df1.merge(df2)
print("Scalanie danych:")
print(df5)

Łączenie po wierszach:
    a    b     c     d      g
0  x1  7.0  10.0   NaN    NaN
1  x2  8.0  11.0   NaN    NaN
2  x3  9.0  12.0   NaN    NaN
0  x1  NaN   NaN  77.0  110.0
1  x2  NaN   NaN  88.0  111.0
2  x3  NaN   NaN  99.0  112.0

Łączenie po kolumnach:
    a  b   c   a   d    g
0  x1  7  10  x1  77  110
1  x2  8  11  x2  88  111
2  x3  9  12  x3  99  112

Scalanie danych:
    a  b   c   d    g
0  x1  7  10  77  110
1  x2  8  11  88  111
2  x3  9  12  99  112